# Uncomment the next line to define a global platform for your project
# platform :ios, '11.2'

target 'MQTTDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'CocoaMQTT'
  # Pods for MQTTDemo

end
